version: '3.9'

services:
  kitten-pgbd:
    build:
      dockerfile: Dockerfile
      context: ./database
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - kitten-pgbd
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
  kitten-backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    environment: 
      - KITTEN_DB_ADDRESS=10.5.0.5
    ports:
      - "5000:5000"
    depends_on:
      - kitten-pgbd
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  
  kitten-frondend:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - kitten-backend
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

volumes:
  postgres-data:
  pgadmin-data:

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1