version: '3.9'

services:
  postgres:
    image: postgres:15.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=your-kitten-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
  #backend:
    #image: your-kitten-backend:latest
    #environment: 
     #   - PORT=8888
    #ports:
     #   - "80:80"
  
  #frondend:
    #image: your-kitten-frontend:latest
    #ports:
        #- "8080:80"

volumes:
  postgres-data:
  pgadmin-data: